In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3924, 5764, 25, 1123],
 [3924, 5764, 25, 7718],
 [3924, 621, 25, 9007],
 [3013, 6291, 8880, 4535, 2431],
 [3013, 6291, 8880, 4535, 4874],
 [4723, 3924, 294, 25, 1001],
 [6034, 827, 6113, 4535]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3924 5764   25 1123]
 [   0    0    0    0 3924 5764   25 7718]
 [   0    0    0    0 3924  621   25 9007]
 [   0    0    0 3013 6291 8880 4535 2431]
 [   0    0    0 3013 6291 8880 4535 4874]
 [   0    0    0 4723 3924  294   25 1001]
 [   0    0    0    0 6034  827 6113 4535]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 126ms/step


array([[[ 0.00337038, -0.03682182,  0.04432564,  0.03495539,
         -0.01571188, -0.03136083, -0.01116036, -0.03440211,
          0.02264518,  0.01333389],
        [ 0.00337038, -0.03682182,  0.04432564,  0.03495539,
         -0.01571188, -0.03136083, -0.01116036, -0.03440211,
          0.02264518,  0.01333389],
        [ 0.00337038, -0.03682182,  0.04432564,  0.03495539,
         -0.01571188, -0.03136083, -0.01116036, -0.03440211,
          0.02264518,  0.01333389],
        [ 0.00337038, -0.03682182,  0.04432564,  0.03495539,
         -0.01571188, -0.03136083, -0.01116036, -0.03440211,
          0.02264518,  0.01333389],
        [-0.04259745, -0.00177072, -0.00245265, -0.03697108,
         -0.00243383, -0.01539332,  0.04911262,  0.01678148,
          0.02927316, -0.02973282],
        [ 0.04734421,  0.00950059,  0.03151293, -0.01350832,
         -0.0103467 ,  0.03771222, -0.02207711, -0.02072095,
          0.04511211,  0.00488517],
        [ 0.04423216,  0.00375789, -0.00612111,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3924, 5764,   25, 1123])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.00337038, -0.03682182,  0.04432564,  0.03495539, -0.01571188,
        -0.03136083, -0.01116036, -0.03440211,  0.02264518,  0.01333389],
       [ 0.00337038, -0.03682182,  0.04432564,  0.03495539, -0.01571188,
        -0.03136083, -0.01116036, -0.03440211,  0.02264518,  0.01333389],
       [ 0.00337038, -0.03682182,  0.04432564,  0.03495539, -0.01571188,
        -0.03136083, -0.01116036, -0.03440211,  0.02264518,  0.01333389],
       [ 0.00337038, -0.03682182,  0.04432564,  0.03495539, -0.01571188,
        -0.03136083, -0.01116036, -0.03440211,  0.02264518,  0.01333389],
       [-0.04259745, -0.00177072, -0.00245265, -0.03697108, -0.00243383,
        -0.01539332,  0.04911262,  0.01678148,  0.02927316, -0.02973282],
       [ 0.04734421,  0.00950059,  0.03151293, -0.01350832, -0.0103467 ,
         0.03771222, -0.02207711, -0.02072095,  0.04511211,  0.00488517],
       [ 0.04423216,  0.00375789, -0.00612111,  0.04075598, -0.00266963,
        -0.00521147,  0.0460507 , -0.04951533